version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wasm-bindgen
    versions:
    - ">= 0.2.46.a, < 0.2.47"
  - dependency-name: wasm-bindgen
    versions:
    - 0.2.70
    - 0.2.71
    - 0.2.72
  - dependency-name: env_logger
    versions:
    - 0.8.2
